package com.zcool.web.dao.model;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.head_image
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    private String headImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.role_type
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    private Integer roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.shop_id
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.open_id
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_login_time
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    private Date lastLoginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.head_image
     *
     * @return the value of user_info.head_image
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    public String getHeadImage() {
        return headImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.head_image
     *
     * @param headImage the value for user_info.head_image
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    public void setHeadImage(String headImage) {
        this.headImage = headImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.role_type
     *
     * @return the value of user_info.role_type
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    public Integer getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.role_type
     *
     * @param roleType the value for user_info.role_type
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    public void setRoleType(Integer roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.shop_id
     *
     * @return the value of user_info.shop_id
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.shop_id
     *
     * @param shopId the value for user_info.shop_id
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.open_id
     *
     * @return the value of user_info.open_id
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.open_id
     *
     * @param openId the value for user_info.open_id
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.last_login_time
     *
     * @return the value of user_info.last_login_time
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.last_login_time
     *
     * @param lastLoginTime the value for user_info.last_login_time
     *
     * @mbggenerated Wed Apr 11 19:08:47 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
}